name: Remote Upload Office
on: [workflow_dispatch]
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download file to Server
        run: |
          wget -O Office2024ProPlusLTSCRu.iso "https://softes.ru"

      - name: Install Rclone
        run: |
          curl https://rclone.org | sudo bash

      - name: Configure Rclone and Upload
        run: |
          mkdir -p ~/.config/rclone
          echo '[gdrive]' > ~/.config/rclone/rclone.conf
          echo 'type = drive' >> ~/.config/rclone/rclone.conf
          echo 'client_id = ://googleusercontent.com' >> ~/.config/rclone/rclone.conf
          echo 'client_secret = v9Tej-gS2f7_H0mHwM423S' >> ~/.config/rclone/rclone.conf
          echo 'scope = drive' >> ~/.config/rclone/rclone.conf
          rclone copy Office2024ProPlusLTSCRu.iso gdrive:${{ secrets.GDRIVE_FOLDER_ID }} --progress
