name: Remote Upload Office
on: [workflow_dispatch]
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download from Softes
        run: |
          wget -O Office2024ProPlusLTSCRu.iso "https://softes.ru"

      - name: Transfer to Free Storage
        run: |
          curl https://bashupload.com --data-binary @Office2024ProPlusLTSCRu.iso
